class CfgPatches
{
	class 53rd_Ares_magear
	{
		author="21st SAB & 53rd";
		requiredAddons[]=
		{
		};
		requiredVersion=0.1;
		units[]={};
		weapons[]=
		{
			"53rd_Ares_RA_H3_Helmet",
			"53rd_Ares_Rifleman_H3_Helmet",
			"53rd_Ares_Medic_H3_Helmet",
			"53rd_Ares_TL_H3_Helmet",
			"53rd_Ares_SL_H3_Helmet",
			"53rd_Ares_PL_H3_Helmet",
			"53rd_Ares_MA_Vest_Rifleman_Normal",
			"53rd_Ares_MA_Vest_Rifleman_CQB",
			"53rd_Ares_MA_Vest_Rifleman_Sniper",
			"53rd_Ares_MA_Vest_PL",
			"53rd_Ares_MA_Vest_PL_CQB",
			"53rd_Ares_MA_Vest_PL_Sniper",
			"53rd_Ares_MA_Vest_SL",
			"53rd_Ares_MA_Vest_SL_CQB",
			"53rd_Ares_MA_Vest_SL_Sniper",
			"53rd_Ares_MA_Vest_TL",
			"53rd_Ares_MA_Vest_TL_CQB",
			"53rd_Ares_MA_Vest_TL_SNIPER",
			"53rd_Ares_MA_Vest_Medic",
			"53rd_Ares_MA_Vest_Medic_Sniper",
			"53rd_Ares_MA_Vest_Medic_CQB",
			
		};
	};
};
class CfgWeapons
{
	class MA_Vest_Base;
	class VestItem;
	class MA_M56R_Vest;
	class ItemInfo;
	class HeadgearItem;
//////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////Helmets/////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////
	class MA_Helmet_Base
	{
	class ItemInfo;
	};
	class MA_M56SH_Helmet: MA_Helmet_Base
	{
	class ItemInfo;
	};
	class 53rd_Ares_RA_H3_Helmet: MA_M56SH_Helmet
	{
			scope=2;
			scopeCurator=2;
			scopeArsenal=2;
			side=1;
			class XtdGearInfo
			{
			};
			displayName="[53rd] Ares RA Helmet";
			model="MA_Armor\data\Helmets\H3_ODST\H3_ODST_Helmet.p3d";
			picture="MA_Armor\data\Icons\H3_ODST_Helmet.paa";
			hiddenSelectionsTextures[]=
			{
				"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_Helmet_RA.paa",
				"MA_Armor\data\Helmets\H3_ODST\H3_Visor_Black_co.paa"
			};
		class ItemInfo: HeadgearItem
		{
			uniformModel="";
			mass=40;
			modelSides[]={6};
			allowedSlots[]={801,901,701,605};
			hiddenSelections[]=
			{
				"camo1",
				"camo2"
			};
			hiddenSelectionsTextures[]={};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=45;
					passThrough=0.1;
				};
				class Face
				{
					hitpointName="HitFace";
					armor=45;
					passThrough=0.1;
				};
				class Neck
				{
					hitpointName="HitNeck";
					armor=40;
					passThrough=0.1;
				};
			};
		};
	};
	class 53rd_Ares_Rifleman_H3_Helmet: MA_M56SH_Helmet
	{
			scope=2;
			scopeCurator=2;
			scopeArsenal=2;
			side=1;
			class XtdGearInfo
			{
			};
			displayName="[53rd] Ares Rifleman Helmet";
			model="MA_Armor\data\Helmets\H3_ODST\H3_ODST_Helmet.p3d";
			picture="MA_Armor\data\Icons\H3_ODST_Helmet.paa";
			hiddenSelectionsTextures[]=
			{
				"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_Helmet_Slotted_Riflemen.paa",
				"MA_Armor\data\Helmets\H3_ODST\H3_Visor_Black_co.paa"
			};
			class ItemInfo: HeadgearItem
			{
				uniformModel="";
				mass=40;
				modelSides[]={6};
				allowedSlots[]={801,901,701,605};
				hiddenSelections[]=
				{
					"camo1",
					"camo2"
				};
				hiddenSelectionsTextures[]={};
				class HitpointsProtectionInfo
				{
					class Head
					{
						hitpointName="HitHead";
						armor=45;
						passThrough=0.1;
					};
					class Face
					{
						hitpointName="HitFace";
						armor=45;
						passThrough=0.1;
					};
					class Neck
					{
						hitpointName="HitNeck";
						armor=40;
						passThrough=0.1;
					};
				};
			};
	};
	class 53rd_Ares_Medic_H3_Helmet: MA_M56SH_Helmet
	{
			scope=2;
			scopeCurator=2;
			scopeArsenal=2;
			side=1;
			class XtdGearInfo
			{
			};
			displayName="(53rd) Ares Medic Helmet";
			model="MA_Armor\data\Helmets\H3_ODST\H3_ODST_Helmet.p3d";
			picture="MA_Armor\data\Icons\H3_ODST_Helmet.paa";
			
			hiddenSelectionsTextures[]=
			{
				"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_Helmet_Medic.paa",
				"MA_Armor\data\Helmets\H3_ODST\H3_Visor_Black_co.paa"
			};
			class ItemInfo: HeadgearItem
			{
				uniformModel="";
				mass=40;
				modelSides[]={6};
				allowedSlots[]={801,901,701,605};
				hiddenSelections[]=
				{
					"camo1",
					"camo2"
				};
				hiddenSelectionsTextures[]={};
				class HitpointsProtectionInfo
				{
					class Head
					{
						hitpointName="HitHead";
						armor=45;
						passThrough=0.1;
					};
					class Face
					{
						hitpointName="HitFace";
						armor=45;
						passThrough=0.1;
					};
					class Neck
					{
						hitpointName="HitNeck";
						armor=40;
						passThrough=0.1;
					};
				};
			};
	};
	class 53rd_Ares_TL_H3_Helmet: MA_M56SH_Helmet
	{
			scope=2;
			scopeCurator=2;
			scopeArsenal=2;
			side=1;
			class XtdGearInfo
			{
			};
			displayName="[53rd] Ares TL Helmet";
			model="MA_Armor\data\Helmets\H3_ODST\H3_ODST_Helmet.p3d";
			picture="MA_Armor\data\Icons\H3_ODST_Helmet.paa";
			hiddenSelectionsTextures[]=
			{
				"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_Helmet_TL.paa",
				"MA_Armor\data\Helmets\H3_ODST\H3_Visor_Black_co.paa"
			};
			class ItemInfo: HeadgearItem
			{
				uniformModel="";
				mass=40;
				modelSides[]={6};
				allowedSlots[]={801,901,701,605};
				hiddenSelections[]=
				{
					"camo1",
					"camo2"
				};
				hiddenSelectionsTextures[]={};
				class HitpointsProtectionInfo
				{
					class Head
					{
						hitpointName="HitHead";
						armor=45;
						passThrough=0.1;
					};
					class Face
					{
						hitpointName="HitFace";
						armor=45;
						passThrough=0.1;
					};
					class Neck
					{
						hitpointName="HitNeck";
						armor=40;
						passThrough=0.1;
					};
				};
			};
	};
	class 53rd_Ares_SL_H3_Helmet: MA_M56SH_Helmet
	{
			scope=2;
			scopeCurator=2;
			scopeArsenal=2;
			side=1;
			displayName="[53rd] Ares SL Helmet";
			model="MA_Armor\data\Helmets\H3_ODST\H3_ODST_Helmet.p3d";
			picture="MA_Armor\data\Icons\H3_ODST_Helmet.paa";
			class XtdGearInfo
			{
			};
			hiddenSelectionsTextures[]=
			{
				"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_Helmet_SL.paa",
				"MA_Armor\data\Helmets\H3_ODST\H3_Visor_Black_co.paa"
			};
			class ItemInfo: HeadgearItem
			{
				uniformModel="";
				mass=40;
				modelSides[]={6};
				allowedSlots[]={801,901,701,605};
				hiddenSelections[]=
				{
					"camo1",
					"camo2"
				};
				hiddenSelectionsTextures[]={};
				class HitpointsProtectionInfo
				{
					class Head
					{
						hitpointName="HitHead";
						armor=45;
						passThrough=0.1;
					};
					class Face
					{
						hitpointName="HitFace";
						armor=45;
						passThrough=0.1;
					};
					class Neck
					{
						hitpointName="HitNeck";
						armor=40;
						passThrough=0.1;
					};
				};
			};
	};
	class 53rd_Ares_PL_H3_Helmet: MA_M56SH_Helmet
	{
			scope=2;
			scopeCurator=2;
			scopeArsenal=2;
			side=1;
			class XtdGearInfo
			{
			};
			displayName="[53rd] Ares PL Helmet";
			model="MA_Armor\data\Helmets\H3_ODST\H3_ODST_Helmet.p3d";
			picture="MA_Armor\data\Icons\H3_ODST_Helmet.paa";
			hiddenSelectionsTextures[]=
			{
				"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_Helmet_PL.paa",
				"MA_Armor\data\Helmets\H3_ODST\H3_Visor_Black_co.paa"
			};
			class ItemInfo: HeadgearItem
			{
				uniformModel="";
				mass=40;
				modelSides[]={6};
				allowedSlots[]={801,901,701,605};
				hiddenSelections[]=
				{
					"camo1",
					"camo2"
				};
				hiddenSelectionsTextures[]={};
				class HitpointsProtectionInfo
				{
					class Head
					{
						hitpointName="HitHead";
						armor=45;
						passThrough=0.1;
					};
					class Face
					{
						hitpointName="HitFace";
						armor=45;
						passThrough=0.1;
					};
					class Neck
					{
						hitpointName="HitNeck";
						armor=40;
						passThrough=0.1;
					};
				};
			};
	};
//////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////ARMOR///////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////
	class 53rd_Ares_MA_Vest_Base: MA_Vest_Base
	{
		scope=1;
		scopeArsenal=1;
		author="53rd SAB";
		displayName="[53rd] MA Base Vest";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			"Canisters"
		};
		hiddenSelectionsTextures[]={};
		class ItemInfo: VestItem
		{
			vestType="Rebreather";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			"Canisters"
			};
			hiddenSelectionsTextures[]=
			{
				"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
				"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
				"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
				"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
				"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
				"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
				"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
				"MA_Armor\data\Vests\Reach_ODST\Addons\Sniper_Shoulders\Sniper_co.paa",
				"MA_Armor\data\Vests\Reach_ODST\Addons\CQB_Shoulders\CQB_co.paa",
				"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
			containerClass="Supply200";
			mass=20;
			passThrough=0.1;
			modelSides[]={6};
			class HitpointsProtectionInfo
			{
				class Neck
				{
					hitpointName="HitNeck";
					armor=40;
					passThrough=0.1;
				};
				class Arms
				{
					hitpointName="HitArms";
					armor=45;
					passThrough=0.1;
				};
				class Chest
				{
					hitpointName="HitChest";
					armor=40;
					passThrough=0.1;
				};
				class Diaphragm
				{
					hitpointName="HitDiaphragm";
					armor=45;
					passThrough=0.1;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=45;
					passThrough=0.1;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.1;
					armor=40;
				};
				class Legs
				{
					hitpointName="HitLegs";
					armor=40;
					passThrough=0.1;
				};
			};
		};
	};
	class 53rd_Ares_MA_Vest_RA: 53rd_Ares_MA_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares RA Armor";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="MA_Armor\data\Icons\H3ODST_Vest.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			//"H3_Pauldron_Left",
			//"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_Upper_Armor_RA.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_Sniper_RA.paa",
			"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_CQB_RA.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
						"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			//"H3_Pauldron_Left",
			//"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
			hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_Upper_Armor_RA.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_Sniper_RA.paa",
			"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_CQB_RA.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		vestType = "Rebreather";
		modelSides[]={6};
	};
	class 53rd_Ares_MA_Vest_RA_CQB: 53rd_Ares_MA_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares RA CQB";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="MA_Armor\data\Icons\H3ODST_Vest.paa";
		hiddenSelections[]=
		{
		"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			//"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_Upper_Armor_RA.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_Sniper_RA.paa",
			"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_CQB_RA.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			//"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
			hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_Upper_Armor_RA.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_Sniper_RA.paa",
			"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_CQB_RA.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		};
		containerClass="Supply200";
		mass=20;
		vestType = "Rebreather";
		passThrough=0.1;
		modelSides[]={6};
	};
	class 53rd_Ares_MA_Vest_RA_Sniper: 53rd_Ares_MA_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares RA Sniper";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="MA_Armor\data\Icons\H3ODST_Vest.paa";
		hiddenSelections[]=
		{
		"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			//"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_Upper_Armor_RA.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_Sniper_RA.paa",
			"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_CQB_RA.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			//"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
			hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_Upper_Armor_RA.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_Sniper_RA.paa",
			"53rd_SC_aux\Armor\Ares_Camo\RA\53rd_3rd_PLT_H3_CQB_RA.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		};
		containerClass="Supply200";
		mass=20;
		vestType = "Rebreather";
		passThrough=0.1;
		modelSides[]={6};
	};
	class 53rd_Ares_MA_Vest_Rifleman: 53rd_Ares_MA_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares Rifleman Armor";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="MA_Armor\data\Icons\H3ODST_Vest.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			//"H3_Pauldron_Left",
			//"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_Upper_Armor_Slotted_Riflemen.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_Snipper_Slotted_Riflemen.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_CQB_Slotted_Riflemen.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
						"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			//"H3_Pauldron_Left",
			//"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
			hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_Upper_Armor_Slotted_Riflemen.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_Snipper_Slotted_Riflemen.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_CQB_Slotted_Riflemen.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		vestType = "Rebreather";
		modelSides[]={6};
	};
	class 53rd_Ares_MA_Vest_Rifleman_CQB: 53rd_Ares_MA_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares Rifleman CQB";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="MA_Armor\data\Icons\H3ODST_Vest.paa";
		hiddenSelections[]=
		{
		"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			//"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_Upper_Armor_Slotted_Riflemen.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_Snipper_Slotted_Riflemen.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_CQB_Slotted_Riflemen.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			//"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
			hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_Upper_Armor_Slotted_Riflemen.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_Snipper_Slotted_Riflemen.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_CQB_Slotted_Riflemen.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		};
		containerClass="Supply200";
        vestType = "Rebreather";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};
	class 53rd_Ares_MA_Vest_Rifleman_Sniper: 53rd_Ares_MA_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares Rifleman Sniper";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="MA_Armor\data\Icons\H3ODST_Vest.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			//"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_Upper_Armor_Slotted_Riflemen.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_Snipper_Slotted_Riflemen.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_CQB_Slotted_Riflemen.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			//"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
			hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_Upper_Armor_Slotted_Riflemen.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_Snipper_Slotted_Riflemen.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Rifleman\53rd_3rd_PLT_H3_CQB_Slotted_Riflemen.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		};
		containerClass="Supply200";
		mass=20;
		vestType = "Rebreather";
		passThrough=0.1;
		modelSides[]={6};
	};
	class 53rd_Ares_MA_Vest_PL: 53rd_Ares_MA_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares PL Armor";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="MA_Armor\data\Icons\H3ODST_Vest.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			//"H3_Pauldron_Left",
			//"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_Upper_Armor_PL.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_Sniper_PL.paa",
			"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_CQB_PL.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			//"H3_Pauldron_Left",
			//"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
				"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_Upper_Armor_PL.paa",
				"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
				"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
				"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
				"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
				"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
				"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
				"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_Sniper_PL.paa",
				"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_CQB_PL.paa",
				"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		};
		containerClass="Supply200";
		mass=20;
		vestType = "Rebreather";
		passThrough=0.1;
		modelSides[]={6};
	};
	class 53rd_Ares_MA_Vest_PL_CQB: 53rd_Ares_MA_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares PL Armor CQB";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="MA_Armor\data\Icons\H3ODST_Vest.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			//"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_Upper_Armor_PL.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_Sniper_PL.paa",
			"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_CQB_PL.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			//"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
			hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_Upper_Armor_PL.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_Sniper_PL.paa",
			"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_CQB_PL.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		};
		containerClass="Supply200";
		mass=20;
		vestType = "Rebreather";
		passThrough=0.1;
		modelSides[]={6};
	};
	class 53rd_Ares_MA_Vest_PL_Sniper: 53rd_Ares_MA_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares PL Armor Sniper";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="MA_Armor\data\Icons\H3ODST_Vest.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			//"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_Upper_Armor_PL.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_Sniper_PL.paa",
			"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_CQB_PL.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			//"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
			hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_Upper_Armor_PL.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_Sniper_PL.paa",
			"53rd_SC_aux\Armor\Ares_Camo\PL\53rd_3rd_PLT_H3_CQB_SPL.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};
	class 53rd_Ares_MA_Vest_SL: 53rd_Ares_MA_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares SL Armor";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="MA_Armor\data\Icons\H3ODST_Vest.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			//"H3_Pauldron_Left",
			//"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_Upper_Armor_SL.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_Sniper_SL.paa",
			"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_CQB_SL.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			//"H3_Pauldron_Left",
			//"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
			hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_Upper_Armor_SL.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_Sniper_SL.paa",
			"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_CQB_SL.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};
	class 53rd_Ares_MA_Vest_SL_CQB: 53rd_Ares_MA_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares SL Armor CQB";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="MA_Armor\data\Icons\H3ODST_Vest.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			//"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_Upper_Armor_SL.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_Sniper_SL.paa",
			"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_CQB_SL.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			//"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
			hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_Upper_Armor_SL.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_Sniper_SL.paa",
			"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_CQB_SL.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};
	class 53rd_Ares_MA_Vest_SL_Sniper: 53rd_Ares_MA_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares SL Armor Sniper";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="MA_Armor\data\Icons\H3ODST_Vest.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			//"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_Upper_Armor_SL.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_Sniper_SL.paa",
			"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_CQB_SL.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			//"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
			hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_Upper_Armor_SL.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_Sniper_SL.paa",
			"53rd_SC_aux\Armor\Ares_Camo\SL\53rd_3rd_PLT_H3_CQB_SL.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};
	class 53rd_Ares_MA_Vest_TL: 53rd_Ares_MA_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares TL Armor";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="MA_Armor\data\Icons\H3ODST_Vest.paa";
		hiddenSelections[]=
		{
						"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			//"H3_Pauldron_Left",
			//"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_Upper_Armor_TL.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_Sniper_TL.paa",
			"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_CQB_TL.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
						"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			//"H3_Pauldron_Left",
			//"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
			hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_Upper_Armor_TL.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_Sniper_TL.paa",
			"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_CQB_TL.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};
	class 53rd_Ares_MA_Vest_TL_CQB: 53rd_Ares_MA_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares TL Armor CBQ";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="MA_Armor\data\Icons\H3ODST_Vest.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			//"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_Upper_Armor_TL.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_Sniper_TL.paa",
			"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_CQB_TL.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			//"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
			hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_Upper_Armor_TL.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_Sniper_TL.paa",
			"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_CQB_TL.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};
	class 53rd_Ares_MA_Vest_TL_SNIPER: 53rd_Ares_MA_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares TL Armor Sniper";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="MA_Armor\data\Icons\H3ODST_Vest.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			//"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_Upper_Armor_TL.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_Sniper_TL.paa",
			"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_CQB_TL.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			//"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
			hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_Upper_Armor_TL.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_Sniper_TL.paa",
			"53rd_SC_aux\Armor\Ares_Camo\TL\53rd_3rd_PLT_H3_CQB_TL.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};
	class 53rd_Ares_MA_Vest_Medic_CQB: 53rd_Ares_MA_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares Medic Armor CQB";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="MA_Armor\data\Icons\H3ODST_Vest.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			//"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_Upper_Armor_Medic.paa",       //camo1 (H3 Upper Armor)
            "MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",       //camo2 (H3 Lower Armor)
            "MA_Armor\data\Vests\H3_ODST\Addons\Medic_Thigh_Pouch_co.paa",//camo3 (Thigh Pouch)
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_Sniper_Medic.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_CQB_Medic.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			//"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
			hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_Upper_Armor_Medic.paa",       //camo1 (H3 Upper Armor)
            "MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",       //camo2 (H3 Lower Armor)
            "MA_Armor\data\Vests\H3_ODST\Addons\Medic_Thigh_Pouch_co.paa",//camo3 (Thigh Pouch)
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_Sniper_Medic.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_CQB_Medic.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};
	class 53rd_Ares_MA_Vest_Medic_Sniper: 53rd_Ares_MA_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares Medic Armor Sniper";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="MA_Armor\data\Icons\H3ODST_Vest.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			//"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_Upper_Armor_Medic.paa",       //camo1 (H3 Upper Armor)
            "MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",       //camo2 (H3 Lower Armor)
            "MA_Armor\data\Vests\H3_ODST\Addons\Medic_Thigh_Pouch_co.paa",//camo3 (Thigh Pouch)
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_Sniper_Medic.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_CQB_Medic.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			//"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
			hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_Upper_Armor_Medic.paa",       //camo1 (H3 Upper Armor)
            "MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",       //camo2 (H3 Lower Armor)
            "MA_Armor\data\Vests\H3_ODST\Addons\Medic_Thigh_Pouch_co.paa",//camo3 (Thigh Pouch)
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_Sniper_Medic.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_CQB_Medic.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};
	class 53rd_Ares_MA_Vest_Medic: 53rd_Ares_MA_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares Medic Armor";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="MA_Armor\data\Icons\H3ODST_Vest.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			//"H3_Pauldron_Left",
			//"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_Upper_Armor_Medic.paa",       //camo1 (H3 Upper Armor)
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_Upper_Armor_Medic.paa",      //camo2 (H3 Lower Armor)
            "MA_Armor\data\Vests\H3_ODST\Addons\Medic_Thigh_Pouch_co.paa",//camo3 (Thigh Pouch)
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_Sniper_Medic.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_CQB_Medic.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			//"H3_Forearm_Left",
			//"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			//"H3_Pauldron_Left",
			//"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
			hiddenSelectionsTextures[]=
			{
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_Upper_Armor_Medic.paa",       //camo1 (H3 Upper Armor)
            "MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",       //camo2 (H3 Lower Armor)
            "MA_Armor\data\Vests\H3_ODST\Addons\Medic_Thigh_Pouch_co.paa",//camo3 (Thigh Pouch)
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Upper_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Reach_Armor_Lower_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"MA_Armor\data\Vests\Reach_ODST\Forearm_Vents_co.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_Sniper_Medic.paa",
			"53rd_SC_aux\Armor\Ares_Camo\Medic\53rd_3rd_PLT_H3_CQB_Medic.paa",
			"MA_Armor\data\Vests\Reach_ODST\Addons\Reach_Shoulder_Radio\Shoulder_Radio_Green_co.paa"
			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};
};

