class CfgPatches {
    class 53rd_Nox_Armor
    {
            units[] = 
            {

            };
            weapons[] = 
            {
			"53rd_Nox_Vest_Red_Urban",
			"53rd_Nox_Vest_Red_Rifleman_Urban",
			"53rd_Nox_Vest_Red_Woodland",
			"53rd_Nox_Vest_Red_Winter",
			"53rd_Nox_Vest_Red_Desert",
			"53rd_Nox_Vest_Blue_Urban",
			"53rd_Nox_Vest_Blue_Rifleman_Urban",
			"53rd_Nox_Vest_Blue_Woodland",
			"53rd_Nox_Vest_Blue_Winter",
			"53rd_Nox_Vest_Blue_Desert",
			"53rd_Nox_Vest_Red_Ghillie_Urban,",
			"53rd_Nox_Vest_Red_Rifleman_Ghillie_Urban",
			"53rd_Nox_Vest_Red_Ghillie_Woodland",
			"53rd_Nox_Vest_Red_Ghillie_Winter",
			"53rd_Nox_Vest_Red_Ghillie_Desert",
			"53rd_Nox_Vest_Blue_Ghillie_Urban,",
			"53rd_Nox_Vest_Blue_Rifleman_Ghillie_Urban",
			"53rd_Nox_Vest_Blue_Ghillie_Woodland",
			"53rd_Nox_Vest_Blue_Ghillie_Winter",
			"53rd_Nox_Vest_Blue_Ghillie_Desert"
            };
            requiredVersion = 0.100000;
            requiredAddons[] = 
			{
				"MA_Armor"
			};
    };
};


class cfgWeapons
{
    class ItemCore;
    class ItemInfo;

//////////////////////////////////////////////////////////////////////////////
///////////////////////////////VEST///////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////
	class 53rd_Ares_Vest_Base;

///////////////////////////////RED///////////////////////////////////////////

	class 53rd_Nox_Vest_Red_Urban: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Urban / Red)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Urban_Lead.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Urban_Lead.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Urban_Lead.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Urban_Lead.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Urban_Lead.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Urban_Lead.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};

	class 53rd_Nox_Vest_Red_Rifleman_Urban: 53rd_Nox_Vest_Red_Urban
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Urban / Red)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Urban_Rifleman.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Urban_Rifleman.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Urban_Rifleman.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};

	class 53rd_Nox_Vest_Red_Woodland: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Woodland / Red)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Woodland_Red.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Woodland_Red.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Woodland.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Woodland.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Woodland_Red.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Woodland_Red.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Woodland.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Woodland.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};

	class 53rd_Nox_Vest_Red_Winter: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Winter / Red)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Winter_Red.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Winter_Red.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Winter.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Winter.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Winter_Red.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Winter_Red.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Winter.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Winter.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};

	class 53rd_Nox_Vest_Red_Desert: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Desert / Red)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Desert_Red.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Desert_Red.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Desert.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Desert.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			//"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Desert_Red.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Desert_Red.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Desert.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Desert.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};


///////////////////////////////BLUE///////////////////////////////////////////

	class 53rd_Nox_Vest_Blue_Urban: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Urban / Blue)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Urban_Lead.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Urban_Lead.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Urban_Lead.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Urban_Rifleman.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Urban_Lead.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Urban_Lead.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Urban_Lead.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Urban_Rifleman.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};


	class 53rd_Nox_Vest_Blue_Rifleman_Urban: 53rd_Nox_Vest_Blue_Urban
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Urban / Blue)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Urban_Rifleman.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Urban_Rifleman.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Urban_Rifleman.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Urban_Rifleman.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};

	class 53rd_Nox_Vest_Blue_Woodland: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Woodland / Blue)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Woodland_Blue.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Woodland_Blue.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Woodland.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Woodland.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Woodland_Blue.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Woodland_Blue.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Woodland.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Woodland.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};

	class 53rd_Nox_Vest_Blue_Winter: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Winter / Blue)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Winter_Blue.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Winter_Blue.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Winter.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Winter.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Winter_Blue.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Winter_Blue.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Winter.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Winter.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};

	class 53rd_Nox_Vest_Blue_Desert: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Desert / Blue)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Desert_Blue.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Desert_Blue.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Desert.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Desert.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			//"Reach_Forearm_Left",
			//"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			//"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			//"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			//"Forearm_Vent_Left",
			//"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Desert_Blue.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Desert_Blue.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Desert.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Desert.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};

///////////////////////////////////////////////////////////////////////////////
//////////////////////////////Ghillie/////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////RED///////////////////////////////////////////

	class 53rd_Nox_Vest_Red_Ghillie_Urban: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Urban / Red)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Urban_Lead.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Urban_Lead.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Urban_Lead.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Urban_Lead.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Urban_Rifleman.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};

	class 53rd_Nox_Vest_Red_Rifleman_Ghillie_Urban: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Urban / Red)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Urban_Rifleman.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Urban_Rifleman.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Urban_Rifleman.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Urban_Rifleman.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};
	
	class 53rd_Nox_Vest_Red_Ghillie_Woodland: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Woodland / Red)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Woodland_Red.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Woodland_Red.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Woodland.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Woodland.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Woodland_Red.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Woodland_Red.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Woodland.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Woodland.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};

	class 53rd_Nox_Vest_Red_Ghillie_Winter: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Winter / Red)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Winter_Red.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Winter_Red.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Winter.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Winter.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Winter_Red.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Winter_Red.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Winter.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Winter.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};

	class 53rd_Nox_Vest_Red_Ghillie_Desert: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Desert / Red)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Desert_Red.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Desert_Red.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Desert.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Desert.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Desert_Red.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Desert_Red.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Desert.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Desert.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};


///////////////////////////////BLUE///////////////////////////////////////////

	class 53rd_Nox_Vest_Blue_Ghillie_Urban: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Urban / Blue)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Urban_Lead.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Urban_Lead.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Urban_Rifleman.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Urban_Lead.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Urban_Lead.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Urban_Rifleman.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};

	class 53rd_Nox_Vest_Blue_Rifleman_Ghillie_Urban: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Urban / Blue)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Urban_Rifleman.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Urban_Rifleman.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Urban_Rifleman.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Urban_Rifleman.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Urban_Rifleman.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};

	class 53rd_Nox_Vest_Blue_Ghillie_Woodland: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Woodland / Blue)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Woodland_Blue.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Woodland_Blue.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Woodland.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Woodland.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Woodland_Blue.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Woodland_Blue.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Woodland.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Woodland.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};

	class 53rd_Nox_Vest_Blue_Ghillie_Winter: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Winter / Blue)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Winter_Blue.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Winter_Blue.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Winter.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Winter.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Winter_Blue.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Winter_Blue.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Winter.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Winter.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};

	class 53rd_Nox_Vest_Blue_Ghillie_Desert: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Nox (Desert / Blue)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Nox.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
		};
		hiddenSelectionsTextures[]=
		{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Desert_Blue.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Desert_Blue.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Desert.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Desert.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
		};
		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			"H3_Armor_Upper",
			"H3_Armor_Lower",
			//"Reach_Armor_Upper",
			//"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"MA_Armor\data\Vests\H3_ODST\H3_Upper_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\H3_Lower_Armor_co.paa",
			"MA_Armor\data\Vests\H3_ODST\Addons\Thigh_Pouch_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Upper_Desert_Blue.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Lower_Desert_Blue.paa",
			"MA_Armor\data\Vests\Reach_ODST\Canisters_co.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Nox_Forearm.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_Sniper_Desert.paa",
			"\53rd_Aux\Ares\Nox\vests\53rd_Shoulder_CQB_Desert.paa",	
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"

			};
		};
		containerClass="Supply200";
		mass=20;
		passThrough=0.1;
		modelSides[]={6};
	};




};