    class 53rd_Aqua_Recon: 53rd_Ares_Recon_Base 
    {
        author="53rd Texture Team";
        scope=2;
        scopeArsenal=2;
        side=1;
        displayName="[53rd] Ares Custom (Aqyrys)";
        model= "\OPTRE_UNSC_Units\Army\recon_helmet.p3d";
        hiddenSelections[]=
        {
            "Camo",
            "Camo2",
            "H_Ghillie"            
        };
        hiddenSelectionsTextures[]=
        {
            "\53rd_Aux\Ares\Customs\Aqyrys\53rd_Aqyrys_Recon_Helmet.paa",
            "\53rd_Aux\Ares\Customs\Recon_Visor.paa"
        };
    };
	
	
	class 53rd_Ares_Aqyrys_Vest: 53rd_Ares_Vest_Base
	{
		scope=2;
		scopeArsenal=2;
		displayName="[53rd] Ares Custom Armor (Aqyrys)";
		model="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
		picture="\53rd_Aux\Functions\Arsenal\Ares.paa";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"\53rd_Aux\Ares\Customs\Aqyrys\53rd_Aqyrys_Upper_Armor.paa",
			"\53rd_Aux\Ares\Customs\Aqyrys\53rd_Aqyrys_Lower_Armor.paa",
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Armor_Thigh_Pouch.paa",
			"\53rd_Aux\Ares\Rifleman\53rd_Ares_Armor_Upper_Rifleman.paa",
			"",
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Armor_Canisters.paa",
			"",
			"\53rd_Aux\Ares\Rifleman\53rd_Ares_Armor_Shoulder_Sniper_Rifleman.paa",
			"\53rd_Aux\Ares\Rifleman\53rd_Ares_Armor_Shoulder_CQB_Rifleman.paa",
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
			};

		class ItemInfo: ItemInfo
		{
			vestType="Rebreather";
			uniformModel="MA_Armor\data\Vests\H3_ODST\H3_ODST_Armor.p3d";
			containerClass="Supply200";
			hiddenSelections[]=
			{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6",
			"camo7",
			"camo8",
			"camo9",
			"camo10",
			"H3_Forearm_Left",
			"H3_Forearm_Right",
			"Reach_Forearm_Left",
			"Reach_Forearm_Right",
			"H3_Pauldron_Left",
			"H3_Pauldron_Right",
			"Reach_Pauldron_Left",
			"Reach_Pauldron_Right",
			"Reach_Shoulder_Radio_Left",
			"Reach_Shoulder_Radio_Right",
			"Reach_Sniper_Pauldron_Left",
			"Reach_Sniper_Pauldron_Right",
			"Reach_CQB_Pauldron_Left",
			"Reach_CQB_Pauldron_Right",
			"Thigh_Pouch",
			//"H3_Armor_Upper",
			//"H3_Armor_Lower",
			"Reach_Armor_Upper",
			"Reach_Armor_Lower",
			"Forearm_Vent_Left",
			"Forearm_Vent_Right",
			//"Canisters"
			};
		hiddenSelectionsTextures[]=
			{
			"\53rd_Aux\Ares\Customs\Aqyrys\53rd_Aqyrys_Upper_Armor.paa",
			"\53rd_Aux\Ares\Customs\Aqyrys\53rd_Aqyrys_Lower_Armor.paa",
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Armor_Thigh_Pouch.paa",
			"\53rd_Aux\Ares\Rifleman\53rd_Ares_Armor_Upper_Rifleman.paa",
			"",
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Armor_Canisters.paa",
			"",
			"\53rd_Aux\Ares\Rifleman\53rd_Ares_Armor_Shoulder_Sniper_Rifleman.paa",
			"\53rd_Aux\Ares\Rifleman\53rd_Ares_Armor_Shoulder_CQB_Rifleman.paa",
			"\53rd_Aux\Ares\Pieces\53rd_Ares_Shoulder_Radio.paa"
			};
		};
		containerClass="Supply200";
		mass=20;
		vestType = "Rebreather";
		passThrough=0.1;
		modelSides[]={6};
	};
